// Generates reference/observers/fixtures/kalman_dare_dmsd.h by running the
// DRE iteration to convergence on the discretised double-mass-spring-damper.
// Run with:  ./export_kalman_dare > fixtures/kalman_dare_dmsd.h

#include <Eigen/Dense>
#include <unsupported/Eigen/MatrixFunctions>
#include <cstdio>
#include <cstdint>
#include "plant_hash.h"

int main() {
    // Default DMSD parameters
    const double m1 = 1.0, m2 = 1.0;
    const double k1 = 10.0, k2 = 10.0;
    const double c1 = 0.5,  c2 = 0.5;
    const double dt = 0.01;
    const double q_scale = 1e-4;
    const double r_scale = 1e-2;

    // Continuous-time state matrix  (states: x1, v1, x2, v2)
    Eigen::Matrix4d Ac;
    Ac <<  0,           1,          0,         0,
          -(k1+k2)/m1, -(c1+c2)/m1, k2/m1,   c2/m1,
           0,           0,          0,         1,
           k2/m2,       c2/m2,     -k2/m2,   -c2/m2;

    // Discrete-time transition matrix via zero-order hold
    Eigen::Matrix4d F = (Ac * dt).exp();

    // Measurement matrix: observe positions x1 and x2
    Eigen::Matrix<double, 2, 4> H;
    H << 1, 0, 0, 0,
         0, 0, 1, 0;

    // Noise covariances
    Eigen::Matrix4d Q = q_scale * Eigen::Matrix4d::Identity();
    Eigen::Matrix2d R = r_scale * Eigen::Matrix2d::Identity();

    // DRE iteration: P_{k+1} = F P_k F^T + Q - F P_k H^T (H P_k H^T + R)^{-1} H P_k F^T
    Eigen::Matrix4d P = Eigen::Matrix4d::Identity();
    int iter = 0;
    for (; iter < 200000; ++iter) {
        Eigen::Matrix<double, 4, 2> FPHt = F * P * H.transpose();
        Eigen::Matrix2d S   = H * P * H.transpose() + R;
        Eigen::Matrix4d P_new = F * P * F.transpose() + Q
                                - FPHt * S.llt().solve(FPHt.transpose());
        P_new = 0.5 * (P_new + P_new.transpose());  // enforce symmetry
        double delta = (P_new - P).norm() / (1.0 + P.norm());
        P = P_new;
        if (delta < 1e-14) break;
    }

    // Steady-state Kalman gain
    Eigen::Matrix2d S_inf = H * P * H.transpose() + R;
    Eigen::Matrix<double, 4, 2> K_inf =
        P * H.transpose() * S_inf.llt().solve(Eigen::Matrix2d::Identity());

    // Plant hash
    uint64_t ph = kalman_dare_dmsd_plant_hash(
        m1, m2, k1, k2, c1, c2, dt, q_scale, r_scale);

    std::fprintf(stderr, "DRE converged in %d iterations\n", iter + 1);
    std::fprintf(stderr, "Plant hash: 0x%016llx\n", (unsigned long long)ph);

    std::printf("// AUTO-GENERATED by tools/gen_oracle_fixtures.py — DO NOT EDIT\n");
    std::printf("// Regenerate: python3 tools/gen_oracle_fixtures.py > fixtures/kalman_dare_dmsd.h\n");
    std::printf("#pragma once\n");
    std::printf("#include <Eigen/Dense>\n");
    std::printf("#include <cstdint>\n");
    std::printf("\n");
    std::printf("namespace caliburn::fixtures {\n");
    std::printf("\n");
    std::printf("// DJB2-64 of the parameter string used by gen_oracle_fixtures.py.\n");
    std::printf("// test_oracle_fixtures recomputes this at runtime; a mismatch means\n");
    std::printf("// the fixture is stale (STALE FIXTURE).\n");
    std::printf("constexpr uint64_t KALMAN_DARE_DMSD_PLANT_HASH = 0x%016llxULL;\n",
                (unsigned long long)ph);
    std::printf("\n");
    std::printf("// Steady-state Kalman gain K_inf (4 x 2)\n");
    std::printf("// System: double-mass-spring-damper\n");
    std::printf("//   m1=%.17g  m2=%.17g  k1=%.17g  k2=%.17g  c1=%.17g  c2=%.17g\n",
                m1, m2, k1, k2, c1, c2);
    std::printf("//   dt=%.17g   Q=%.17g*I4   R=%.17g*I2\n", dt, q_scale, r_scale);
    std::printf("// Oracle: SciPy scipy.linalg.solve_discrete_are\n");
    std::printf("static inline Eigen::Matrix<double, 4, 2> kalman_dare_K_inf() {\n");
    std::printf("    Eigen::Matrix<double, 4, 2> K;\n");
    std::printf("    // clang-format off\n");
    std::printf("    K <<\n");
    for (int i = 0; i < 4; ++i) {
        std::printf("        %.17g, %.17g", K_inf(i, 0), K_inf(i, 1));
        if (i < 3) std::printf(",\n");
        else        std::printf(";\n");
    }
    std::printf("    // clang-format on\n");
    std::printf("    return K;\n");
    std::printf("}\n");
    std::printf("\n");
    std::printf("}  // namespace caliburn::fixtures\n");

    return 0;
}
