#!/usr/bin/env python3
"""Generate observers/fixtures/kalman_dare_dmsd.h with SciPy's solve_discrete_are.

Usage (from reference/):
    cmake --build build --target export_kalman_dare
    ./build/export_kalman_dare | python3 observers/tools/gen_oracle_fixtures.py - \\
        > observers/fixtures/kalman_dare_dmsd.h

Reads the plant (F, H, Q, R) and its hash from export_kalman_dare's JSON, so
the oracle solves exactly the matrices the C++ filter runs on; this script
knows nothing about the model.  Solves the filter DARE

    P = F P F' + Q - F P H' (H P H' + R)^-1 H P F'

as SciPy's control-form DARE with a = F', b = H', and emits the steady-state
gain K_inf = P H' (H P H' + R)^-1, where P is the pre-update covariance.

SciPy is required; there is no fallback.  Ported from ball-balancer's
tools/gen_oracle_fixtures.py.
"""

import json
import sys
from datetime import date

try:
    import numpy as np
    import scipy
    import scipy.linalg
except ImportError as e:
    print(f"SciPy is not installed: {e}", file=sys.stderr)
    sys.exit(1)


def parse_matrix(s: str) -> np.ndarray:
    return np.array([[float(x) for x in row.split()] for row in s.split(";")])


def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] == "-":
        plant = json.load(sys.stdin)
    else:
        with open(sys.argv[1]) as fh:
            plant = json.load(fh)

    F = parse_matrix(plant["F"])
    H = parse_matrix(plant["H"])
    Q = parse_matrix(plant["Q"])
    R = parse_matrix(plant["R"])

    P = scipy.linalg.solve_discrete_are(F.T, H.T, Q, R)
    S = H @ P @ H.T + R
    K = np.linalg.solve(S.T, (P @ H.T).T).T  # P H' S^-1

    n, m = K.shape
    lines = [
        "// observers/fixtures/kalman_dare_dmsd.h",
        "// Generated by observers/tools/gen_oracle_fixtures.py -- DO NOT EDIT.",
        "// Re-run the pipeline to regenerate (from reference/):",
        "//   cmake --build build --target export_kalman_dare",
        "//   ./build/export_kalman_dare | python3 observers/tools/gen_oracle_fixtures.py - \\",
        "//       > observers/fixtures/kalman_dare_dmsd.h",
        "//",
        f"// Oracle: scipy {scipy.__version__} solve_discrete_are",
        f"// Date  : {date.today()}",
        "//",
        f"// Plant : {plant['name']} (see observers/tools/kalman_dare_plant.h)",
        f"// K_inf : {n}x{m} steady-state Kalman gain, from the pre-update covariance",
        "#pragma once",
        "",
        "#include <Eigen/Dense>",
        "#include <cstdint>",
        "",
        "namespace caliburn::fixtures {",
        "",
        "// Recomputed from the live plant by test_kalman_oracle; a mismatch is a",
        "// stale fixture.",
        f"constexpr uint64_t KALMAN_DARE_DMSD_PLANT_HASH = 0x{plant['plant_hash']}ULL;",
        "",
        f"inline Eigen::Matrix<double, {n}, {m}> kalman_dare_K_inf() {{",
        f"    Eigen::Matrix<double, {n}, {m}> K;",
    ]
    for i in range(n):
        for j in range(m):
            lines.append(f"    K({i}, {j}) = {K[i, j]:.17g};")
    lines += [
        "    return K;",
        "}",
        "",
        "}  // namespace caliburn::fixtures",
        "",
    ]
    print("\n".join(lines), end="")


if __name__ == "__main__":
    main()
