#!/usr/bin/env python3
"""Generate fixtures/kalman_dare_dmsd.h using SciPy's solve_discrete_are.

Usage:
    python3 tools/gen_oracle_fixtures.py > fixtures/kalman_dare_dmsd.h

The fixture contains the steady-state Kalman gain K_inf for the
double-mass-spring-damper with default parameters, and a DJB2-64 plant hash
used by test_oracle_fixtures to detect staleness.
"""

import sys
import struct

try:
    import numpy as np
    import scipy.linalg
    from scipy.signal import cont2discrete
except ImportError as e:
    print(f"SciPy is not installed: {e}", file=sys.stderr)
    sys.exit(1)

# ---------------------------------------------------------------------------
# Plant parameters — must match export_kalman_dare.cpp and test_oracle_fixtures.cpp
# ---------------------------------------------------------------------------
m1, m2 = 1.0, 1.0
k1, k2 = 10.0, 10.0
c1, c2 = 0.5, 0.5
dt      = 0.01
q_scale = 1e-4
r_scale = 1e-2

# Continuous-time state matrix  (states: x1, v1, x2, v2)
Ac = np.array([
    [0,            1,           0,          0         ],
    [-(k1+k2)/m1, -(c1+c2)/m1,  k2/m1,    c2/m1    ],
    [0,            0,           0,          1         ],
    [k2/m2,        c2/m2,      -k2/m2,    -c2/m2    ],
], dtype=float)

Bc = np.zeros((4, 1))
Bc[3, 0] = 1.0 / m2

Cc = np.array([[1, 0, 0, 0], [0, 0, 1, 0]], dtype=float)

# Discretise using zero-order hold
Fd, _, _, _, _ = cont2discrete((Ac, Bc, Cc, 0), dt, method='zoh')
H = Cc  # measurement matrix unchanged by ZOH

Q = q_scale * np.eye(4)
R = r_scale * np.eye(2)

# ---------------------------------------------------------------------------
# Solve the Kalman DARE via SciPy
# scipy.linalg.solve_discrete_are(a, b, q, r) solves
#   a^H X a - X - (a^H X b)(r + b^H X b)^{-1}(b^H X a) + q = 0
# For the Kalman filter DARE (P = F P F^T + Q - ...) set a=F^T, b=H^T.
# ---------------------------------------------------------------------------
P_inf = scipy.linalg.solve_discrete_are(Fd.T, H.T, Q, R)

S_inf  = H @ P_inf @ H.T + R
K_inf  = P_inf @ H.T @ np.linalg.inv(S_inf)

# ---------------------------------------------------------------------------
# Plant hash: DJB2-64 of the canonical parameter string
# (must reproduce the same value as plant_hash.h: kalman_dare_dmsd_plant_hash)
# ---------------------------------------------------------------------------
def djb2_64(s: str) -> int:
    h = 5381
    for c in s.encode():
        h = ((h << 5) + h) ^ c
        h &= 0xFFFFFFFFFFFFFFFF
    return h

param_str = (
    f"kalman-dare-dmsd:"
    f"m1={m1:.17g},m2={m2:.17g},"
    f"k1={k1:.17g},k2={k2:.17g},"
    f"c1={c1:.17g},c2={c2:.17g},"
    f"dt={dt:.17g},"
    f"q={q_scale:.17g}*I4,r={r_scale:.17g}*I2"
)
plant_hash = djb2_64(param_str)

# ---------------------------------------------------------------------------
# Emit the fixture header
# ---------------------------------------------------------------------------
print("// AUTO-GENERATED by tools/gen_oracle_fixtures.py — DO NOT EDIT")
print("// Regenerate: python3 tools/gen_oracle_fixtures.py > fixtures/kalman_dare_dmsd.h")
print("#pragma once")
print("#include <Eigen/Dense>")
print("#include <cstdint>")
print()
print("namespace caliburn::fixtures {")
print()
print("// DJB2-64 of the parameter string used by gen_oracle_fixtures.py.")
print("// test_oracle_fixtures recomputes this at runtime; a mismatch means")
print("// the fixture is stale (STALE FIXTURE).")
print(f"constexpr uint64_t KALMAN_DARE_DMSD_PLANT_HASH = 0x{plant_hash:016x}ULL;")
print()
print("// Steady-state Kalman gain K_inf (4 x 2)")
print("// System: double-mass-spring-damper")
print(f"//   m1={m1}  m2={m2}  k1={k1}  k2={k2}  c1={c1}  c2={c2}")
print(f"//   dt={dt}   Q={q_scale}*I4   R={r_scale}*I2")
print("// Oracle: SciPy scipy.linalg.solve_discrete_are")
print("static inline Eigen::Matrix<double, 4, 2> kalman_dare_K_inf() {")
print("    Eigen::Matrix<double, 4, 2> K;")
print("    // clang-format off")
rows = []
for i in range(4):
    rows.append(f"        {K_inf[i,0]:.17g}, {K_inf[i,1]:.17g}")
print("    K <<\n" + ",\n".join(rows) + ";")
print("    // clang-format on")
print("    return K;")
print("}")
print()
print("}  // namespace caliburn::fixtures")
