// observers/fixtures/kalman_dare_dmsd.h
// Generated by observers/tools/gen_oracle_fixtures.py -- DO NOT EDIT.
// Re-run the pipeline to regenerate (from reference/):
//   cmake --build build --target export_kalman_dare
//   ./build/export_kalman_dare | python3 observers/tools/gen_oracle_fixtures.py - \
//       > observers/fixtures/kalman_dare_dmsd.h
//
// Oracle: scipy 1.18.1 solve_discrete_are
// Date  : 2026-10-04
//
// Plant : double-mass-spring-damper (see observers/tools/kalman_dare_plant.h)
// K_inf : 4x2 steady-state Kalman gain, from the pre-update covariance
#pragma once

#include <Eigen/Dense>
#include <cstdint>

namespace caliburn::fixtures {

// Recomputed from the live plant by test_kalman_oracle; a mismatch is a
// stale fixture.
constexpr uint64_t KALMAN_DARE_DMSD_PLANT_HASH = 0xe5591a227d134030ULL;

inline Eigen::Matrix<double, 4, 2> kalman_dare_K_inf() {
    Eigen::Matrix<double, 4, 2> K;
    K(0, 0) = 0.091685367326673678;
    K(0, 1) = 0.0048913422709492387;
    K(1, 0) = -0.034069315234727476;
    K(1, 1) = 0.050842782828959418;
    K(2, 0) = 0.0048913422709492387;
    K(2, 1) = 0.096576709597622407;
    K(3, 0) = 0.050842782828961507;
    K(3, 1) = 0.016773467594232382;
    return K;
}

}  // namespace caliburn::fixtures
