// AUTO-GENERATED by tools/gen_oracle_fixtures.py — DO NOT EDIT
// Regenerate: python3 tools/gen_oracle_fixtures.py > fixtures/kalman_dare_dmsd.h
#pragma once
#include <Eigen/Dense>
#include <cstdint>

namespace caliburn::fixtures {

// DJB2-64 of the parameter string used by gen_oracle_fixtures.py.
// test_oracle_fixtures recomputes this at runtime; a mismatch means
// the fixture is stale (STALE FIXTURE).
constexpr uint64_t KALMAN_DARE_DMSD_PLANT_HASH = 0x2984d674a215c523ULL;

// Steady-state Kalman gain K_inf (4 x 2)
// System: double-mass-spring-damper
//   m1=1  m2=1  k1=10  k2=10  c1=0.5  c2=0.5
//   dt=0.01   Q=0.0001*I4   R=0.01*I2
// Oracle: SciPy scipy.linalg.solve_discrete_are
static inline Eigen::Matrix<double, 4, 2> kalman_dare_K_inf() {
    Eigen::Matrix<double, 4, 2> K;
    // clang-format off
    K <<
        0.091685367326795331, 0.0048913422711475227,
        -0.034069315233530226, 0.050842782830910156,
        0.0048913422711475227, 0.096576709597943219,
        0.050842782830909899, 0.016773467597382297;
    // clang-format on
    return K;
}

}  // namespace caliburn::fixtures
